version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - 8000:5432
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
      - POSTGRES_HOST=db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5454:5454/tcp
    environment:
      PGADMIN_DEFAULT_EMAIL: db@db.com
      PGADMIN_DEFAULT_PASSWORD: db
      PGADMIN_LISTEN_PORT: 5454
volumes:
  postgres_data: